name:                ranvid
version:             0.1.0.0
github:              "Rintse/ranvid"
license:             BSD-3-Clause
author:              "Rintse"
copyright:           "2024 Rintse"
build-type:          Custom

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/rintse/ranvid#readme>

dependencies:
- base >= 4.7 && < 5
- split
- NoTrace
- parallel
- haskore
- unordered-containers
- mtl
- hip
- array
- recursion-schemes
- monadic-recursion-schemes
- inflist
- binary
- random
- bytestring
- generic-random
- QuickCheck
- QuickCheck-GenT
- MonadRandom

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

custom-setup:
  dependencies:
  - base
  - Cabal
  - process

library:
  source-dirs: src
  generated-exposed-modules: 
  - Syntax.Grammar.Par
  - Syntax.Grammar.Lex
  - Syntax.Grammar.Abs
  - Syntax.Grammar.ErrM
  - Syntax.Grammar.Print

flags:
  debug:
    description: Enable debug printing of generator
    manual: True
    default: False

when:
  - condition: flag(debug)
    cpp-options:  -DDEBUG

executables:
  ranvid_img:
    main:         Main.hs
    source-dirs:  app_image
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ranvid
  ranvid_music:
    main:         Main.hs
    source-dirs:  app_music
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ranvid
  ranvid_test:
    main:         Main.hs
    source-dirs:  test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ranvid
